Repository BSData/The-9th-Age, pull requests merged in 2019-11, with the labels that each got.

#506 Daemon Legions 2.3.1
  daemonLegions.cat
Labels: bug, versionupdate

#508 2.1.5 update: Beast Herds
  beastHerds.cat
Labels: enhancement, versionupdate

#513 2.1.5 Update: Dread Elves
  dreadElves.cat
Labels: enhancement, versionupdate

#510 ID 2.1.5 update + fixed default selections
  infernalDwarves.cat
Labels: versionupdate

#525 2.1.5 update: Highborn Elves
  highbornElves.cat
Labels: bug, enhancement, versionupdate

#527 Ud2.1.5
  undyingDynasties.cat
Labels: enhancement, versionupdate

#529 Fix #516
  warriorsOfTheDarkGods.cat
Labels: bug

#539 2.1.5 update: Kingdom of Equitaine
  kingdomOfEquitaine.cat
Labels: enhancement, versionupdate

#543 VC 2.1.5
  vampireCovenant.cat
Labels: bug, enhancement, versionupdate

#544 VC 2.1.5: Dominant restrictions on VC items
  vampireCovenant.cat
Labels: enhancement

#549 2.1.5 Update: Sylvan Elves
  sylvanElves.cat
Labels: enhancement, versionupdate

#558 Ong 2.1.5 Update
  dreadElves.cat
  orcsAndGoblins.cat
Labels: bug, enhancement, versionupdate

#575 HE: Let Royal Huntsman choose a mount
  highbornElves.cat
Labels: bug

#576 OnG: Fix Goblin Raiders equipment costs
  orcsAndGoblins.cat
Labels: bug

#578 OnG: Iron Orc Chief point costs
  orcsAndGoblins.cat
Labels: bug

#582 2.1.5 Update: Cultists
  cultists.cat
Labels: enhancement, versionupdate

#584 OK: Shaman Cult General now allowed
  ogreKhans.cat
Labels: bug

#585 ID: Vizier Shamut Bull point costs
  infernalDwarves.cat
Labels: bug

#586 BH: Enchantments and selections update
  beastHerds.cat
Labels: enhancement
