Repository BSData/The-9th-Age, pull requests merged in 2019-10, with the labels that each got.

#387 Cultists
  cultists.cat
Labels: enhancement, versionupdate

#388 Fixed Symbol of Slaughter rules text
  asklanders.cat
Labels: bug

#392 2.1 update: KoE
  kingdomOfEquitaine.cat
Labels: versionupdate

#394 V2.1 update
  vampireCovenant.cat
  warriorsOfTheDarkGods.cat
Labels: versionupdate

#397 V2.1update
  dreadElves.cat
  dwarvenHolds.cat
  infernalDwarves.cat
  ogreKhans.cat
  saurianAncients.cat
  sylvanElves.cat
  theVerminSwarm.cat
  vampireCovenant.cat
Labels: versionupdate

#404 2.1 update: Mak
  makhar.cat
Labels: versionupdate

#406 Bugfix: Costs for DC Hierarch and Tomb Cataphracts
  undyingDynasties.cat
Labels: bug

#423 2.1fixes
  dreadElves.cat
  empireOfSonnstahl.cat
Labels: bug

#426 WDG: Chosen Lord Banner Enchantments via Trophy R.
  warriorsOfTheDarkGods.cat
Labels: bug

#429 Fix #419 - 2.1 Update: HE
  highbornElves.cat
Labels: versionupdate

#442 2.1.2 update: SA
  saurianAncients.cat
Labels: versionupdate

#443 2.1.1 update: SE
  sylvanElves.cat
Labels: enhancement, versionupdate

#444 Fix Kuulima's Deceiver rules and magic
  daemonLegions.cat
Labels: bug, enhancement

#448 Add "rules" to def- and offensive profiles
  theNinthAge-FantasyBattles.gst
Labels: enhancement

#449 2.1.1update
  cultists.cat
  daemonLegions.cat
Labels: bug, enhancement

#451 Fix points for Elein Reavers and Queen's Cavalier
  highbornElves.cat
Labels: bug

#459 Move Manifestations directly onto top level
  daemonLegions.cat
Labels: enhancement

#461 2.1 update: VS
  theVerminSwarm.cat
Labels: enhancement, versionupdate

#462 2.1 update: OnG
  orcsAndGoblins.cat
Labels: versionupdate

#465 ID: Prophet Path Selection
  infernalDwarves.cat
Labels: enhancement

#466 Magic paths
  sylvanElves.cat
  vampireCovenant.cat
Labels: enhancement

#472 War cry costs
  empireOfSonnstahl.cat
  orcsAndGoblins.cat
Labels: bug

#473 Giant Club upgrade cost corrected
  orcsAndGoblins.cat
Labels: bug

#489 Asklander Update
  asklanders.cat
Labels: bug, enhancement

#491 Fix point cost of Mystic Traveller
  saurianAncients.cat
Labels: bug

#494 Infernal Engine Shrapnel Gun counts for Barrage
  infernalDwarves.cat
Labels: bug

#495 Huge Vampire Covenant Update
  vampireCovenant.cat
Labels: bug, enhancement

#496 Size profile
  beastHerds.cat
  dwarvenHolds.cat
  highbornElves.cat
  infernalDwarves.cat
  kingdomOfEquitaine.cat
  makhar.cat
  ogreKhans.cat
  orcsAndGoblins.cat
  theVerminSwarm.cat
  warriorsOfTheDarkGods.cat
Labels: enhancement
